name: marketplaceIndexer
project_type: no-code
networks:
    - name: sepolia
      chain_id: 11155111
      rpc: ${SEPOLIA_RPC_URL}
      rpc_config:
          batch_size: 400 # Process 400 blocks at a time (safely under 500 limit)
          requests_per_second: 10 # Limit requests to avoid rate limiting
storage:
    postgres:
        enabled: true
    csv:
        enabled: true
        path: ./generated_csv
native_transfers:
    enabled: false
contracts:
    - name: NftMarketplace
      details:
          - network: sepolia
            address: 0xdba9d270059eb6d21d61b7c58a95d87c4d872305
            start_block: "8381240"
            # end_block: "19000000"
      abi: ./abis/NFTMarketplace.abi.json
      include_events:
          - ItemListed
          - ItemCanceled
          - ItemBought
